### ISSUE TITLE
2.13inch_e-Paper_HAT_(B) not working

### ISSUE THREAD

**Issue by michnapiotr** [veebch/btcticker#100]
I have tried to apply your steps using raspberry pi zero W and 2.13inch e-Paper HAT (B)

https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(B)

Unfortunately it did not work.

Is this type of 2.13inch e-paper suitable for your approach?

**Comment by veebch** [comment]
@TheRockaXXX has definitely got it working. I *think* it was that screen
