### ISSUE TITLE
Font size problem

### ISSUE THREAD

**Issue by SzilagyiR** [veebch/btcticker#101]
Hi!

Thanks for your wok, it's amazing!

I'm trying to show the price in HUF, but it contains too many number: HUF16,286975
How can I reduce the font size, to fit it on the screen?

Thanks!

**Comment by veebch** [comment]
It's good to see that prices are getting too big for the screen :)
I will try to make it automatic as soon as I get a chance. For a quick fix, line 315. Change from 50 to a smaller number :)

**Comment by SzilagyiR** [comment]
Thanks for the fast solution, it is perfect now! Font size is 35

![IMG_5765](https://user-images.githubusercontent.com/26599357/160469928-8a1f83c6-b812-41c4-a66c-4e16a25721c7.jpg)

**Comment by veebch** [comment]
Excellent.... another line that might interest you is 283, where you can change the locale.

**Comment by SzilagyiR** [comment]
More than perfect! :)
![IMG_5766](https://user-images.githubusercontent.com/26599357/160475692-c73fccee-a470-4b2d-8cf2-0e59f7b48caa.jpg)

**Comment by veebch** [comment]
Excellent. And for full satisfaction, pull gently on the green tab to remove the screen protector :)

**Comment by SzilagyiR** [comment]
Sure, but first I print it a nice house for it with a screen protector :)

**Comment by veebch** [comment]
I just thought I'd mention it because I didn't realise it was there for ages :) Enjoy watching the price!

**Comment by veebch** [comment]
I've just added locale to the config file and an automatic scaling. Not tested yet, that's after coffee

**Comment by SzilagyiR** [comment]
Don't feel like implement this project into yours?
https://github.com/aCallum/NicePi

It would be good because don’t need a separate PI for it. :)

**Comment by veebch** [comment]
Funnily enough, this was something I was looking at doing.

The locale addition to the config file is a good one. Thanks for reminding me to do it.
