### ISSUE TITLE
Divide by zero bug

### ISSUE THREAD

**Issue by adamneilson** [veebch/btcticker#102]
The last few days I've been experiencing an issue with my beloved ticker where it crashes with an error "Issue float division by zero Line: 450"

I'm tracking the following: BTC, ALGO and XAU

I have to restart the pi to get it running again. I'm not sure what other details I can give as there's not much to display on the epaper screen but happy to elaborate if needed.

**Comment by veebch** [comment]
I've seen that error on old code. Have you pulled the latest version. That should at least give a better error message if it does fail

**Comment by adamneilson** [comment]
i just pulled latest updating from 13566ee to f339809. Fingers crossed!

**Comment by adamneilson** [comment]
i just pulled latest updating from 13566ee to f339809. Fingers crossed!

**Comment by adamneilson** [comment]
Two hours later and no further occurrence so I'll close this issue.

**Comment by adamneilson** [comment]
Unfortunately the problem still exists. The error changed slightly but still not very verbose:

_"Issue: float division by zero Line: 454"_

**Comment by veebch** [comment]
Useful! It's happening in MakeSpark. I will look into it

**Comment by veebch** [comment]
I have a copy running with your configuration on. I will try to reproduce the error

**Comment by adamneilson** [comment]
👍

**Comment by adamneilson** [comment]
Oh! I just checked my conf and it's actually PAXG not XAU. So my config is:
```
currency: algorand,bitcoin,pax-gold
```

**Comment by veebch** [comment]
OK..... I will change it. Most likely it was this:

https://status.coingecko.com/incidents/81704

**Comment by veebch** [comment]
Still running here. What about you?

**Comment by adamneilson** [comment]
Yeah, it's running well here. I guess it must have been coingecko API problems. It might be good to catch the API connection error and display an appropriate message on screen but that's definitely a nice to have rather than an essential :)

**Comment by veebch** [comment]
Yeah, the error trapping could definitely be tidied. It's on the to-do list
:)

**Comment by adamneilson** [comment]
https://status.coingecko.com is saying there's no issues but I've been having the same error as before this afternoon. @veebch is yours working okay?

**Comment by veebch** [comment]
It is.... What are your coins and refresh time?

**Comment by adamneilson** [comment]
currency: algorand,bitcoin,pax-gold with refresh time of 120 seconds

**Comment by veebch** [comment]
I've not seen any problems yet. I'll keep an eye on it. Regardless, the error trapping sucks..... moving it up my to-do list

**Comment by adamneilson** [comment]
Is there a log file somewhere that I could grep?

**Comment by veebch** [comment]
You could check dmesg or just run it interactively from the terminal with the debug flag:
`python3 btcticker.py --log DEBUG`
