### ISSUE TITLE
someone copied your project...

### ISSUE THREAD

**Issue by reddai75** [veebch/btcticker#104]
I just  found that someone copied your project and put it on sale. He made a stock ticker version also. I can't find the code anywhere. It's a shame that he does not share it. Here it is https://www.etsy.com/listing/1106931566/stock-ticker-on-electronic-paper-75inch?click_key=6620bf3037652d2ffb1a765ead7b9969aa3b3016%3A1106931566&click_sum=e7ee3b15&ref=shop_home_active_4&crt=1&sts=1

**Comment by veebch** [comment]
:) I've seen that, and mailed them a while ago about including a link to the original source in their ad. They added it.

...it's a pity they never submitted the modifications they made back to the repository so that people making their own would have the stocks option too.
