### ISSUE TITLE
Display always shows the running potato ;D "Issue: 0 Check your connection. Error at Line: 510

### ISSUE THREAD

**Issue by TheRockaXXX** [veebch/btcticker#112]
Hi,
first of all, i really like your project. Thanks a lot.
But after my first (positiv) experience i always get the message above. I still can connect via ssh and the raspberry catches the right date and time. The connection to the network works, I think, the connection to coingecko failed. But I can't figure the reason.
Can someone help please?

**Comment by veebch** [comment]
Running potato :)

Try logging onto the pi and pinging the coingecko api (curl https://api.coingecko.com/api/v3/ping) from there. 

If you can see it, try going back to the example config.yaml file, that will help you locate the problem.

**Comment by TheRockaXXX** [comment]
Gecko says: "To the moon!" :D Ok, that works.
I checked the example config and compared it with mine (show below) and can't find any possible mistake.
`pi@cointicker:~/btcticker $ cat config.yaml 
display:
  24h: true
  cycle: false
  inverted: false
  locale: de_DE
  orientation: 90
  showrank: false
  showvolume: false
  trendingmode: false
ticker:
  currency: bitcoin
  exchange: default
  fiatcurrency: eur
  sparklinedays: 1
  updatefrequency: 120
`

**Comment by veebch** [comment]
The whitespace in yaml files is important too. Try making a copy of your file and replading it with the example one. 

```
mv config.yaml config_old.yaml
cp config_example.yaml config.yaml
python3 btcticker.py
```

**Comment by TheRockaXXX** [comment]
Same behavior. Same message on the screen :(. I think, I have to reinstall everything.  
I can't understand, why the connection to coingecko works (ping) and the price update doesnt. Maybe my ip is blacklisted?

**Comment by TheRockaXXX** [comment]
I found out, that coingecko had a DDoS attack and was down a lot of time in the last few days. 
So, today i copied my modified config (same as before the problems) and it worked. 
Thanks for your fast and helpful support!!!
