### ISSUE TITLE
externally-managed-environment

### ISSUE THREAD

**Issue by will0913** [veebch/btcticker#133]
I was following along the instructions, and everything was working quite nicely until I hit
`python3 -m pip install -r requirements.txt`, where the error message says "This environment is extremely managed"

![PXL_20240701_172215668](https://github.com/veebch/btcticker/assets/94770856/06a04453-2331-4fb6-a039-08b310f27819)

Therefore, I was getting errors about missing modules.

Your assistance is greatly appreciated.

**Comment by veebch** [comment]
Here's a nice little article that should explain how to proceed:
https://learn.adafruit.com/python-virtual-environment-usage-on-raspberry-pi/overview

**Comment by will0913** [comment]
Thanks for much for the quick response. Though other unrelated issues arose, the ones with venv have been resolved.
