### ISSUE TITLE
running on a esp32

### ISSUE THREAD

**Issue by reddai75** [veebch/btcticker#90]
would be possible to create a version for the esp32? I’m just wondering…. how difficult would be to port the code?

**Comment by llvllch** [comment]
By going to micropython you would need to use different libraries. Definitely doable, I know that at least one person has done it.

**Comment by reddai75** [comment]
> By going to micropython you would need to use different libraries. Definitely doable, I know that at least one person has done it.

great, is it available on github ?

**Comment by veebch** [comment]
not that I'm aware of
