### ISSUE TITLE
Issue ‘prices’ Line 436

### ISSUE THREAD

**Issue by PDM78** [veebch/btcticker#94]
As subject above, I’m getting this error code periodically. 
![E771FEE0-A3D8-4E45-AFB8-CA374B870774](https://user-images.githubusercontent.com/94618042/143323072-8869f338-84b2-463c-aa43-5425a9e82358.jpeg)

Has anyone else encountered this issue?

**Comment by veebch** [comment]
The message is a bit cryptic, but it is when there is a problem pulling the data from coingecko. It could be them doing maintenance or blocking you for too many requests. I noticed them doing a temporary block on my IP if I suddenly started hitting their api fast (seconds apart, multiple script runs).

**Comment by PDM78** [comment]
Got it! Been testing since yesterday and seldom does the message appear. I have the display rotating every 30 seconds.

**Comment by reddai75** [comment]
it's normal if you update every 30 sec. Don't forget that coingecko API is
a free service as long as you don't abuse it.

Il giorno gio 25 nov 2021 alle ore 12:09 PDM78 ***@***.***>
ha scritto:

**Comment by veebch** [comment]
a consideration is that the lifespan of epaper is measured in refreshes, so an epaper refreshing every two minutes will last 4 times longer than one refreshing every 30 seconds

**Comment by reddai75** [comment]
> a consideration is that the lifespan of epaper is measured in refreshes, so an epaper refreshing every two minutes will last 4 times longer than one refreshing every 30 seconds

about that: it would be nice to have the possibility to add a timeframe for sleepmode, like during the night!

**Comment by sterdeus** [comment]
For consideration of energy savings, I think a sleep mode would be negligible. As mentioned, lifespan of the screen would be the main purpose. However, I find myself waking up in the middle of the night and quickly checking bitcoin's price. FOMO to the max.

**Comment by veebch** [comment]
This is the main use-case for me. I dream about a price, wake up, glance at the ticker, see the real price
