### ISSUE TITLE
Can't display Solana

### ISSUE THREAD

**Issue by k3rnelpanic640** [veebch/btcticker#95]
When I add solana to the config.yaml file it gives me the bouncing happy face guy instead of the coin. I've confirmed through coingeko and the tickerhelp.py script that I'm using the correct ID in the file. It works fine for other currencies.

**Comment by veebch** [comment]
Check there is no space after the name. The yaml package gets picky about whitespace. I've tried solana and it works.

**Comment by k3rnelpanic640** [comment]
Thanks. I realized that there was no logo. After I added a properly formatted logo image it worked fine.
