### ISSUE TITLE
waveshare 2.7inch e-Paper HAT screen does not display 

### ISSUE THREAD

**Issue by wasauce** [veebch/btcticker#98]
Setup:
raspberrypi zero W v1.1
waveshare 2.7inch e-Paper HAT

I have connected the waveshare to the raspberrypi zero W v1.1 via the 40 pin connector BUT I have not soldered my pins in on the raspberrypi zero W -- this is a dumb question -- but the waveshare wont be able to connect until I solder the pins right?

**Comment by veebch** [comment]
You could use one of these: 
https://www.adafruit.com/product/3662

**Comment by wasauce** [comment]
Thanks very much!
