### ISSUE TITLE
No screen activity after update 

### ISSUE THREAD

**Issue by TheRockaXXX** [veebch/btcticker#99]
Hi,
after the update two days ago (git pull), the screen doesnt work anymore. No blinking or anything else. The remote access via ssh is still possible. 
do you have any tipps? What was the change in the script 18 days ago?
Thank you!

**Comment by veebch** [comment]
I suspect it was the switch to Babel for taking care of the currencies.

`python3 -m pip install babel' should fix it

**Comment by TheRockaXXX** [comment]
You are absolutely right! Now it works! 
Thanks for your fast response!
